# Generated by Django 3.0.7 on 2020-06-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200613_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
