# Generated by Django 3.0.7 on 2020-06-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200613_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default_profile/default_user.jpg', upload_to=''),
        ),
    ]
