# Generated by Django 3.0.7 on 2020-06-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
