# Generated by Django 2.2.13 on 2020-06-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photo_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_public',
        ),
    ]
