# Generated by Django 2.2.13 on 2020-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_remove_photo_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
